# Generated by Django 4.1.1 on 2022-09-12 07:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('table_package', models.CharField(choices=[('VVIP', 'VVIP'), ('standard', 'standard'), ('premium', 'premium')], max_length=10)),
                ('table_sit', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_photo', models.ImageField(upload_to='customer_photo', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30, verbose_name='menu_name')),
                ('menu_discription', models.TextField()),
                ('menu_photo', models.ImageField(upload_to='menu_photo', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wistara.menu_category')),
            ],
        ),
    ]
