# Generated by Django 4.1.1 on 2022-09-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wistara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcribe',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
