# Generated by Django 4.1.1 on 2022-09-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wistara', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
