# Generated by Django 4.1.1 on 2022-09-11 00:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wistara', '0002_alter_subcribe_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='subcribe',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30)),
                ('menu_discription', models.TextField()),
                ('menu_photo', models.ImageField(upload_to='menu_photo', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wistara.menu_category')),
            ],
        ),
    ]
